"""Stable, client-safe errors emitted by the MCP gateway."""

from enum import Enum

from pydantic import BaseModel


class GatewayErrorCode(str, Enum):
    INVALID_AGENT = "INVALID_AGENT"
    INVALID_TOOL_NAME = "INVALID_TOOL_NAME"
    UNKNOWN_SERVER = "UNKNOWN_SERVER"
    UNKNOWN_TOOL = "UNKNOWN_TOOL"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    POLICY_DENIED = "POLICY_DENIED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    DOWNSTREAM_UNAVAILABLE = "DOWNSTREAM_UNAVAILABLE"
    DOWNSTREAM_TIMEOUT = "DOWNSTREAM_TIMEOUT"
    SECURITY_EVALUATION_FAILED = "SECURITY_EVALUATION_FAILED"
    APPROVAL_NOT_FOUND = "APPROVAL_NOT_FOUND"
    APPROVAL_DENIED = "APPROVAL_DENIED"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    APPROVAL_TIMED_OUT = "APPROVAL_TIMED_OUT"
    APPROVAL_ALREADY_CONSUMED = "APPROVAL_ALREADY_CONSUMED"
    APPROVAL_ARGUMENT_MISMATCH = "APPROVAL_ARGUMENT_MISMATCH"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    SESSION_OWNERSHIP_MISMATCH = "SESSION_OWNERSHIP_MISMATCH"
    AUDIT_EVENT_NOT_FOUND = "AUDIT_EVENT_NOT_FOUND"


class GatewayError(BaseModel):
    code: GatewayErrorCode
    message: str
    request_id: str
    tool_name: str
    decision: str | None = None
    matched_policy: str | None = None
    risk_score: int | None = None
    risk_level: str | None = None
    approval_id: str | None = None
